### ISSUE TITLE
Geração máxima de boletos

### ISSUE THREAD

**Issue by eltonoliveira** [drupalista-br/Boleto#16]
Pessoal, estou gerando boletos usando um convênio do Banco do Brasil, com 6 dígitos e tipo de carteira igual a 18.
Pelo que eu notei esse tipo de convênio só permite gerar no máximo 99.999 boletos.
Quando eu tento gerar mais de 99.999 boletos a geração ocorre sem problemas, mas quando vou validar a linha digitalizável gerada o banco acusa que ela é inválida.
Alguém já teve esse problema? Vocês tiveram de criar um novo número de convênio com o banco?
Muito obrigado!

**Comment by aryribeiro** [comment]
pessoal , como faço pra conseguir a biblioteca bancária 2014/2015 ?? o open boletos e outros estão obsoletos e não funcionam mais, devido a mudanças feitas pela febraban. podem dar uma luz?

**Comment by drupalista-br** [comment]
Ari, poderia citar suas fontes. Eu não estou sabendo desta mudança.

**Comment by aryribeiro** [comment]
minhas fontes são no caso, minha cara quebrada. rs fizemos teste com o open boleto e o banco estornou e não aceitou o pagamento. a última atualização do open boletos foi em 2013. 

eu gostaria de colocar geração de boletos em meu site (www) e deixar os clientes se virando sozinhos ,tirando segunda via de boletos.

**Comment by drupalista-br** [comment]
Ari,
Qual o nome do banco? 
Qual a justificativa para o estorno dada pelo banco?

**Comment by aryribeiro** [comment]
caixa. o que vimos é que usamos uma biblioteca obsoleta e fora das novas normas. você não ficou sabendo de  mudança alguma em 2014 ?

qual biblioteca bancária você usa atualmente? pode postar link pra download?

**Comment by drupalista-br** [comment]
Não sei o que vc quer dizer com "biblioteca bancária". Poderia elaborar como vc chegou a conclusão a forma de se calcular o código de barras para boletos se tornou obsoleto e também o que seria uma "biblioteca bancária".

**Comment by aryribeiro** [comment]
veja esse link: http://garajau.com.br/blog/2013/08/openboleto-geracao-de-boleto-bancario/

nossos termos técnicos são diferentes e como dizem por aí: falamos "linguas diferentes" no mesmo país. 

o que seria o open boletos pra você? 

a questão é que ele não funciona mais. o que poderia ser usado pra substituir o open boletos agora em 2015 ?

essa é a questão principal. como eu não entendo de rede bancária, eu não saberia atualizar o open boletos ou não saberia criar um (gerador de boletos) do zero.

entende?

**Comment by aryribeiro** [comment]
estou para testar esse: https://codeload.github.com/CobreGratis/boletophp/legacy.zip/master
alguém conhece?

**Comment by drupalista-br** [comment]
Tenho a impressão que o não funcionamento está de alguma forma relacionado à configuração deste ( ou qualquer outro ) módulo e não ao fato do módulo ter ficado obsoleto.

É possível, no entanto, que haja um bug no módulo e por isso é importante vc averiguar a resposta do banco quanto a rejeição do boleto.

**Comment by aryribeiro** [comment]
ok. mas vc recomenda outra ferramenta, além do open boletos? qual vc usa?

**Comment by drupalista-br** [comment]
Ari,
Eu escrevi este módulo, então eu sou suspeito para lhe recomendar.

Se vc não entende ( como vc mesmo disse ) como configurar e fazer trouble shooting do sistema, talvez seja melhor vc contratar alguém para executar o serviço para vc ( independente de qual módulo/biblioteca for usada ).

**Comment by aryribeiro** [comment]
se seu módulo está funcionando. então vou fazer novos testes em cima dele.

obrigado.

**Comment by drupalista-br** [comment]
Disponha. Por favor, abra um novo chamado caso precise reportar um bug.

**Comment by aryribeiro** [comment]
já viu isso? http://www.boletocloud.com/

**Comment by drupalista-br** [comment]
Não, não conhecia.
